export const CONSTANTS = {
  jwtAlgorithm: 'HS512',
  jwtExpiredIn: 24 * 60 * 60,
  globalPublicSocketRoomName: 'GLOBAL_PUBLIK',
  orangPentingSocketRoomName: 'ORANG_PENTING',
  cronFansubRssFeed: 'CRON_FANSUB_RSS_FEED',
  cronFansubRssFeedAll: 'CRON_FANSUB_RSS_FEED_ALL',
  timeoutCancelRegister: 'TIMEOUT_CANCEL_REGISTER',
  timeoutDeleteTempAttachment: 'TIMEOUT_DELETE_TEMP_ATTACHMENT',
  hirakataQuizOptionsCount: 5,
  kanjiQuizOptionsCount: 6,
  decoratorRoles: 'roles',
  decoratorVerifiedOnly: 'verified-only',

  allKeyboardKeysRegex: /^[\P{Cc}\P{Cn}\P{Cs}]*$/,
  japaneseKeyboardKeysRegex: /[一-龠ぁ-ゔァ-ヴーａ-ｚＡ-Ｚ０-９々〆〤、。]+/u,
  englishKeyboardKeysRegex: /^[a-zA-Z0-9~`!@#\$%\^&\*\(\)_\-\+={\[\}\]\|\\:;"'<,>\.\?\/  \n]*$/,
  emailRegex: /^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$/,
  urlRegex: /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)/,
};
