export const CONSTANTS = {
  cronFansubRssFeed: 'CRON_FANSUB_RSS_FEED',
  cronFansubRssFeedAll: 'CRON_FANSUB_RSS_FEED_ALL',
  decoratorRoles: 'roles',
  decoratorVerifiedOnly: 'verified-only',
  jwtAlgorithm: 'HS512',
  jwtExpiredIn: 24 * 60 * 60,
  quizOptionsCountHirakata: 5,
  quizOptionsCountKanji: 6,
  regexAllKeyboardKeys: /^[\P{Cc}\P{Cn}\P{Cs}]*$/,
  regexJapaneseKeyboardKeys: /[一-龠ぁ-ゔァ-ヴーａ-ｚＡ-Ｚ０-９々〆〤、。]+/u,
  regexEnglishKeyboardKeys: /^[a-zA-Z0-9~`!@#\$%\^&\*\(\)_\-\+={\[\}\]\|\\:;"'<,>\.\?\/  \n]*$/,
  regexEmail: /^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$/,
  regexUrl: /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)/,
  socketRoomNameGlobalPublic: 'GLOBAL_PUBLIK',
  socketRoomNameOrangPenting: 'ORANG_PENTING',
  timeoutCancelRegister: 'TIMEOUT_CANCEL_REGISTER',
  timeoutDeleteTempAttachment: 'TIMEOUT_DELETE_TEMP_ATTACHMENT',
};
