# FansubID ~ Fansub Indonesia

name: NodeJS Deploy ~ Angular + NestJS

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote SSH commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            sudo pm2 stop fansubid
            cd /home/bifeldy/www/fansubid
            git pull
            npm install
            sudo pm2 restart fansubid
