# FansubID ~ Fansub Indonesia

name: Re-Deploy ー SSH

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH ー RCE
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/app/fansubid
            git pull
            npm install
            sudo pm2 restart fansubid
